### PR TITLE
fix configure/RELEASE and configure/ExampleRELEASE.local

### PR DESCRIPTION
**Pull request by mrkraimer**
Changes relating to comments from Andrew.

Unless I hear objections this will be merged tomorrow 18-Aug-2015.

### CODE REVIEW

**Comment by anjohnson** [comment]
The order of the lines in your configure/RELEASE is reversed, EPICS_BASE should appear _last_, with PVCOMMON immediately above it etc. The original file had the correct order, just with some lines missing.

**Comment by anjohnson** [comment]
The order in the ExampleRELEASE.local is similarly wrong.

**Comment by mrkraimer** [comment]
Andrew can You look and see if order is now correct.
In particular note that in ExampleRELEASE.local the definition of TEMPLATE_TOP is after EPICS_BASE

**Comment by anjohnson** [comment]
Hi Marty, everything looks good now. It doesn't matter where TEMPLATE_TOP occurs in the order, in fact I tend to remove it from finished modules as it's never likely to be used anyway.
- Andrew

**Pull request merged**
